### ISSUE TITLE
Branch of Softether-radaact

### ISSUE THREAD

**Issue by m0zart89** [kosztyua/softether-radacct#1]
https://github.com/m0zart89/softether-radacct

I'm new on githab and don't know how to alert you about my changes so they are:
1)set new regexp mask for start and stop
2)found command to kill zombie processes (pcntl_signal(SIGCHLD, SIG_IGN); )
3)some small changes as path to "vpncmd" and e.t.c.

**Comment by kosztyua** [comment]
Great, send a pull request, will merge your changes this week, I also have some changes locally and will upload
