### ISSUE TITLE
The README.md looks like has an error.

### ISSUE THREAD

**Issue by yasar-luo** [kosztyua/softether-radacct#3]
Hi,
    I just read the project's readme, i found there looks like has an error happen in step.8 "For archiving old log files, setup a crontab with archive.php"
    The source code doesn't exist "archive.php" but "archive.sh", i think maybe you wrote in a mistake?
    Also, i have some questions, can you help me?
    I can't understand how does the syslog_ng work, i googled, but just found a little descriptions about it, can you write a detailed readme about these?such as how to send softether's log to syslog_ng?
    Thanks.

**Comment by kosztyua** [comment]
Hi,
You are right, it should be archive.sh in the README, as it is indeed an sh script. 
Sending softether log to syslog is very easy, just go to Encryption and Network Settings in the Server Manager, and add your syslog server ip on the syslog send function part. I recommend using option 3, send server and virtual hub security logs by syslog. 
Will upgrade some things in the script, but atm busy with other things.
