### ISSUE TITLE
functions.php:getsessiondata($sessid)

### ISSUE THREAD

**Issue by OkkioXavier** [kosztyua/softether-radacct#4]
Should 
if(strpos($SessionGet[0],"rror occurred") != FALSE) { die("Error - SessionGet resulted in error"); 

be 

if(strpos($SessionGet[0],"Error occurred") != FALSE) { die("Error - SessionGet resulted in error"); 

?

**Comment by kosztyua** [comment]
I seem to recall having some reason for doing so, skipping the E from the check. Maybe different errors can occur here and can be lower case too, and didn't remember there was case-insensitive stripos function? In any case, doesn't make much difference, but thank you for noticing :)
