### ISSUE TITLE
PHP Notice:  Undefined offset: 1 in /var/radius/interim.php on line 39

### ISSUE THREAD

**Issue by imizwa** [kosztyua/softether-radacct#6]
Howdy, thanks for writing this and making it public. I have followed your instructions and running on CentOS 7. I am receiving data from VPN to acctstart.php and acctstop.php but when I try running interim.php either manually or via cron I get the following errors. 

```

PHP Notice:  Undefined offset: 1 in /var/radius/interim.php on line 39
PHP Notice:  Undefined offset: 1 in /var/radius/interim.php on line 39
PHP Notice:  Undefined offset: 1 in /var/radius/interim.php on line 39
PHP Notice:  Undefined offset: 1 in /var/radius/interim.php on line 39
PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 1, no such table: sessions in /var/radius/interim.php on line 44
```

I still a beginner with PHP as I normally code C# so would be very much appreciated if you could help me.

cheers!
Richie

**Comment by kosztyua** [comment]
Hey,

I would say there is some kind of issue with sessions.db, either it does not exist or has not been populated yet. To test make sure there are clients connected and radius received accounting data, and run manually the printdb.php. If it shows similar error, check if the perms are OK to create/populate the sessions.db. 

Regards,
Andras

**Comment by anonymouz4** [comment]
Hi,
I got the exact same error.
The file never gets created, exept if I run printdb.php, which creates an empty file.
But acctstart.php never creates anything.

To be sure that the permissions are ok, I even created an extra directory (/var/radius/sessions) to store the .db file and gave everyone permission.

The sending of the logs from SoftEther to Syslog-ng works, bc `/var/log/remote/localhost/localhost/2018/12/23/localhost_2018_12_23.log` contains all the log files.

My config File:
```
source net { udp(); };
destination remote { file("/var/log/remote/${FULLHOST}/${YEAR}/${MONTH}/${DAY}/${HOST}_${YEAR}_${MONTH}_${DAY}.log" create-dirs(yes)); };
log { source(net); destination(remote); };

filter acctstart_192.168.0.1_vpnhub { host(10.1.0.1) and match("VPN") and match("The new session"); };
destination acctstart { program("php /var/radius/acctstart.php" flags(no_multi_line) flush_lines(1) flush_timeout(1000)); };
log { source(net); filter(acctstart_192.168.0.1_vpnhub); destination(acctstart); };

filter acctstop_192.168.0.1_vpnhub { host(10.1.0.1) and match("VPN") and match("The session has been terminated"); };
destination acctstop { program("php /var/radius/acctstop.php" flags(no_multi_line) flush_lines(1) flush_timeout(1000)); };
log { source(net); filter(acctstop_192.168.0.1_vpnhub); destination(acctstop); };
```
To clarify, I have 2 servers.
S1 has the vpn and syslog-ng (sends over localhost) with tap device (tap_vpn) on 10.1.0.1
S2 is the radius server

Have you ever resolved this?

Regards,
John

**Comment by imizwa** [comment]
Hi John, the issue turned out to be broken code and line breaks in the syslog.conf because at the time I was using a client called SmarTTY which is crap, switched to SuperPuTTY as advised by kosztyua and was fine. The other issue was vpncmd was not on the server.

Kosztyua said the following:

"- on the syslog server you did not have vpncmd, which is required for the script to query the softether server
- the syslog.conf was broken (the lines were copied with line breaks in them)"

Hope this helps.

cheers!
Richie

**Comment by jahmac23** [comment]
session.db file is just empty. syslog-ng server working  and receiving data. run radtest.php and it shows "Test was successful". But still its not working. when run interim.php it shows lot of error like php warning and notice error.
this is what I get on interim.php
php -q /var/radius/interim.php
PHP Fatal error:  Can't use function return value in write context in /var/radius/interim.php on line 31

Please if you can send us the working .php files and syslog-ng config file.
I use this config file. just another qsn in syslog-ng config file this host IP is it my vpn server local Gateway IP or what IP I should put.
source net { udp(); };
destination remote { file("/var/log/remote/${FULLHOST}/${YEAR}/${MONTH}/${DAY}/${HOST}_${YEAR}_${MONTH}_${DAY}.log" create-dirs(yes)); };
log { source(net); destination(remote); };

filter acctstart_192.168.0.1_vpnhub { host("192.168.30.1") and match("vpnhub") and match("The new session"); };
destination acctstart { program("php /var/radius/acctstart.php" flags(no_multi_line) flush_lines(1) flush_timeout(1000)); };
log { source(net); filter(acctstart_192.168.0.1_vpnhub); destination(acctstart); };

filter acctstop_192.168.0.1_vpnhub { host("192.168.30.1") and match("vpnhub") and match("The session has been terminated"); };
destination acctstop { program("php /var/radius/acctstop.php" flags(no_multi_line) flush_lines(1) flush_timeout(1000)); };
log { source(net); filter(acctstop_192.168.0.1_vpnhub); destination(acctstop); };

**Comment by jahmac23** [comment]
"> Hey,
> 
> I would say there is some kind of issue with sessions.db, either it does not exist or has not been populated yet. To test make sure there are clients connected and radius received accounting data, and run manually the printdb.php. If it shows similar error, check if the perms are OK to create/populate the sessions.db.
> 
> Regards,
> Andras"

syslog-ng server working and receiving hub security log from sofether vpn server. But still cant get it working. interim.php file giving error msg. printdb.php file giving error. also nothing is written on sessions.db.....its empty.
