### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Octolus** [kosztyua/softether-radacct#7]
Would this allow me to limit it, so users can only have one simultaneous connection at once? 

Right now with Radius, they are able to sign in from multiply locations at once (share their login details, with 30+ clients) with no problem.

I want to limit it so 1 client per login, at once.

**Comment by Octolus** [comment]
My mission, can this be achieved with your script ?

- Multiply VPN Servers
- One radius server for auth.
- Do wildcard account in Softether (*) redirect all to the radius server for auth.
- Allow one user to access all servers, but only one server at once. 

To prevent the user from sharing the login details with friends, or reselling access. It would limit the connections to 1 per user, so user can only use the VPN on 1 device.

**Comment by kosztyua** [comment]
Simultaneous connection limit is decided by RADIUS, but the script will provide accounting data for RADIUS, so it will know how many active connections there are. 
The way you described is exactly what I do with the script.
