### ISSUE TITLE
Empty result

### ISSUE THREAD

**Issue by echodreamz** [kosztyua/softether-radacct#8]
I've enabled "Send Server and Virtual Hub Security Logs by Syslog" - However no database is being created, i tried writing the $input contents to a file in the /tmp directory, the file is created, but is empty.

It seems like Softether is not giving any data to PHP.

**Comment by echodreamz** [comment]
`source net { udp(); };
filter new_session { match("new session"); };
destination remote { file("/var/log/remote/${FULLHOST}/${YEAR}/${MONTH}/${DAY}/${HOST}_${YEAR}_${MONTH}_${DAY}.log" create-dirs(yes)); };
log { source(net); filter(new_session); destination(remote); };`

Tested this as well to see if just new sessions would be written to the log, however nothing gets written to the logs at all.

**Comment by kosztyua** [comment]
Test first simply logging. Is SE server set correctly for remote logging? Does the firewalls accept syslog communication? I'm no syslog expert, but it should be very straightforward to troubleshoot - first reach one simple goal: put all softether log in one file with syslog-ng, then add filters and actions as in sample.

**Comment by echodreamz** [comment]
Yes, if I remove the filter() call it logs perfectly fine.
