### ISSUE TITLE
sessions.db file empty, interim.php and prtintdb.php gives error

### ISSUE THREAD

**Issue by jahmac23** [kosztyua/softether-radacct#9]
Hi, can someone please help me to correct some issue. I setup syslog-ng correctly and its receiving hub security log data all good. The problem is sessions.db file empty. so when I run php /var/radius/interim.php it disconnects current user also gives some error. Also if I run printdb.php it also gives error and still sessions.db file empty.
running on ubuntu 16.04/php7.0...by default it installed php7.0 when I run the command to install.
# php /var/radius/interim.php
error: "PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 1, no such table: sessions in /var/radius/interim.php on line 44
"
also disconnect current online user.

# php /var/radius/printdb.php
Error msg: "PHP Warning:  SQLite3::query(): Unable to prepare statement: 1, no such table: sessions in /var/radius/printdb.php on line 24
PHP Fatal error:  Uncaught Error: Call to a member function fetchArray() on boolean in /var/radius/printdb.php:26
Stack trace:
#0 {main}
  thrown in /var/radius/printdb.php on line 26"
and empty sessions.db file.

Also in syslog-ng conf file what IP address I should use in as host IP and "vpnhub". Do I have to edit according to my softether IPv4 address or softether vpn server  local IP and in "vpnhub" i need to vpnhub name "vpn".

**Comment by kosztyua** [comment]
Interim is really the last step, you should forget about that until everything else works fine, its purpose is just to update the already existing records in the database. Printdb obviously gives error if the session file is empty. 
The way it works is softether logs all security events and sends it through udp to the syslog server. The syslog filter, when specific conditions met (IP and HUB name) and specific events happen (connect, disconnect) then runs the acctstart and acctstop scripts, which will modify the sessions db. If the sessions file is empty, that means the acctstart did not run or ran but with error. 
If you have to ask if you should modify the provided syslog-ng file, think over the above. Yes, if you have different IP and HUB name, you have to modify it accordingly.

**Comment by jahmac23** [comment]
Thanks for your great reply. You explained in details.  May I just thank you from bottom of my heart. Your one reply just solved my last few days effort to get this accounting working.
All working great now. No issue at all.

**Comment by jahmac23** [comment]
The total time shows bit funny though. After I setup cron job every 5 minutes (*/5 * * * *) for interim.php its showing total time 49710 days, 6 hours, 15 minutes, 31 seconds. Traffic counting looks ok. Is there anything I can fix total time.
Also what frequency I should put cron job for archive.sh.....is it once in a day.
And another thing even if I disable user in freeradius the user doest disconnect...still running.  Anything I can do so it disconnects automatically after disable or expired.

**Comment by jahmac23** [comment]
Total time looks ok after 45 mins of use. Please just reply the rest of the query.

**Comment by kosztyua** [comment]
Simply disabling the user in freeradius will not disconnect him, that would require a whole new piece of code. Or you could modify the interim.php to check the users' status, should be fairly easy, but depends on your deployment. Something like foreach active sessions run an sql request if user is active, if not then disconnectsession().  
As for archiving, its purpose is just to make logs more compact and save space. Once a day is the minimum but you could have it weekly or not at all.

**Comment by jahmac23** [comment]
"Something like foreach active sessions run an sql request if user is active, if not then disconnectsession()."
Thanks mate. If its fairly easy code and if you have time may I ask you if you can give me that code  to add  in interim.php to check user status in FreeRadius so it disconnects users when its disabled in Freeradius.

**Comment by kosztyua** [comment]
As I said, it depends on your deployment. But if you make the SQL query part, I could write that other few lines, but don't have time to test or debug if not working.

**Comment by jahmac23** [comment]
"As I said, it depends on your deployment. But if you make the SQL query part"
Thanks mate. I can test myself and update you if its working or not.
I am not sure mate what you wanted to know about deployment. All I can say I use FreeRaidus (ubuntu 18.04 with MySQL setup) authentication with my SoftEther vpn server (ubuntu 16.04). Can you please explain about deployment...not sure what did you mean by deployment and what you want to know.

If you can advise me where to look for SQL part then I can try but not too confident. You may also know the SQL part yourself as you created this whole script. 
Its ok mate.....it all depends if you have time for this.

**Comment by jahmac23** [comment]
After I disabled one user I can see this on my daloradius panel on that user. Not sure you need this.
Debugging SQL Queries: 
SELECT Value FROM radcheck WHERE UserName='user1' AND Attribute like '%Password' SELECT firstname, lastname, email, department, company, workphone, homephone, mobilephone, address, city, state, country, zip, notes, changeuserinfo, portalloginpassword, enableportallogin, creationdate, creationby, updatedate, updateby FROM userinfo WHERE UserName='user1' SELECT planName, contactperson, company, email, phone, address, city, state, country, zip, paymentmethod, cash, creditcardname, creditcardnumber, creditcardverification, creditcardtype, creditcardexp, notes, changeuserbillinfo, lead, coupon, ordertaker, billstatus, lastbill, nextbill, nextinvoicedue, billdue, postalinvoice, faxinvoice, emailinvoice, creationdate, creationby, updatedate, updateby FROM userbillinfo WHERE UserName='user1' SELECT radcheck.Attribute, radcheck.op, radcheck.Value, dictionary.Type, dictionary.RecommendedTooltip, radcheck.id FROM radcheck LEFT JOIN dictionary ON radcheck.Attribute=dictionary.attribute AND dictionary.Value IS NULL WHERE radcheck.UserName='user1' SELECT radreply.Attribute, radreply.op, radreply.Value, dictionary.Type, dictionary.RecommendedTooltip, radreply.id FROM radreply LEFT JOIN dictionary ON radreply.Attribute=dictionary.attribute AND dictionary.Value IS NULL WHERE radreply.UserName='user1'

**Comment by jahmac23** [comment]
After disable user goes to daloRADIUS-Disabled-Users group in my daloradius panel. so if the  user is checked whether its in "daloRADIUS-Disabled-Users" groupname then disconnection. is that something we can run query like this.
in my FreeRadius main/sqlite/queries.conf. Not sure if this can help you to write the php script to check user in groupname ""daloRADIUS-Disabled-Users" and disconnect that users.

sql_user_name = "%{User-Name}"
client_query = "\
	SELECT id, nasname, shortname, type, secret, server \
	FROM ${client_table}"
authorize_check_query = "\
	SELECT id, username, attribute, value, op \
	FROM ${authcheck_table} \
	WHERE username = '%{SQL-User-Name}' \
	ORDER BY id"

authorize_reply_query = "\
	SELECT id, username, attribute, value, op \
	FROM ${authreply_table} \
	WHERE username = '%{SQL-User-Name}' \
	ORDER BY id"

group_membership_query = "\
	SELECT groupname \
	FROM ${usergroup_table} \
	WHERE username = '%{SQL-User-Name}' \
	ORDER BY priority"

authorize_group_check_query = "\
	SELECT id, groupname, attribute, \
	Value, op \
	FROM ${groupcheck_table} \
	WHERE groupname = '%{${group_attribute}}' \
	ORDER BY id"

authorize_group_reply_query = "\
	SELECT id, groupname, attribute, \
	value, op \
	FROM ${groupreply_table} \
	WHERE groupname = '%{${group_attribute}}' \
	ORDER BY id"
